## SIB - P1

A Jupyter Notebook with examples of how to use the Dataset object.
18/09/2023

In [1]:
from si.data.dataset import Dataset
import numpy as np

# create a dataset
X = np.random.rand(150, 30)
y = np.random.randint(0, 2, 150)
dataset = Dataset(X, y)
dataset.shape()

(150, 30)

In [2]:
# get the X
dataset.X

array([[0.85228015, 0.80749453, 0.57486695, ..., 0.67445269, 0.55845254,
        0.8517487 ],
       [0.76383361, 0.78538514, 0.0279985 , ..., 0.59136597, 0.23789901,
        0.20486591],
       [0.45123929, 0.65042743, 0.81298505, ..., 0.87214239, 0.93611507,
        0.65308772],
       ...,
       [0.34742091, 0.94998317, 0.97997618, ..., 0.69629931, 0.22392567,
        0.6283366 ],
       [0.90230521, 0.80952386, 0.96088498, ..., 0.47811387, 0.85292105,
        0.66460364],
       [0.03648708, 0.73332938, 0.24464103, ..., 0.65203076, 0.26080718,
        0.40834504]])

In [3]:
#get the features names
dataset.features

['feat_0',
 'feat_1',
 'feat_2',
 'feat_3',
 'feat_4',
 'feat_5',
 'feat_6',
 'feat_7',
 'feat_8',
 'feat_9',
 'feat_10',
 'feat_11',
 'feat_12',
 'feat_13',
 'feat_14',
 'feat_15',
 'feat_16',
 'feat_17',
 'feat_18',
 'feat_19',
 'feat_20',
 'feat_21',
 'feat_22',
 'feat_23',
 'feat_24',
 'feat_25',
 'feat_26',
 'feat_27',
 'feat_28',
 'feat_29']

In [4]:
# has label?
dataset.has_label()

True

In [5]:
# print the label
dataset.y

array([0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0])

In [6]:
# get classes
dataset.get_classes()

array([0, 1])

In [7]:
# statistics summary
dataset.summary()

feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
mean    0.531235  0.500326  0.504989  0.467080  0.476416  0.504877  0.515107   
median  0.552917  0.493838  0.474359  0.431224  0.448607  0.505083  0.516810   
min     0.002553  0.021472  0.002471  0.004415  0.019876  0.005007  0.001658   
max     0.993245  0.992803  0.995450  0.998042  0.996492  0.999486  0.987209   
var     0.089095  0.077102  0.076819  0.092417  0.080456  0.099040  0.090057   

          feat_7    feat_8    feat_9  ...   feat_20   feat_21   feat_22  \
mean    0.498837  0.521068  0.482569  ...  0.478348  0.499259  0.486483   
median  0.501009  0.539121  0.461260  ...  0.468364  0.488495  0.477117   
min     0.010056  0.000032  0.000651  ...  0.001620  0.018805  0.019779   
max     0.990616  0.994821  0.997407  ...  0.996414  0.997361  0.988195   
var     0.072190  0.076495  0.080048  ...  0.085078  0.085065  0.080870   

         feat_23   feat_24   feat_25   feat_26   feat_27   feat_28   feat_29  
mean    0.447191  0.518180  0.504872  0.516896  0.518139  0.483291  0.484347  
median  0.424582  0.529027  0.477498  0.544002  0.553139  0.421165  0.516975  
min     0.003081  0.003481  0.000480  0.002310  0.007319  0.003209  0.002368  
max     0.994641  0.992292  0.986779  0.985894  0.990336  0.997794  0.997862  
var     0.084287  0.078365  0.087306  0.078911  0.082462  0.079398  0.077689  

[5 rows x 30 columns]

In [8]:
from si.io.data_file import read_data_file

# read breast dataset from data file
breast_dataset = read_data_file('../datasets/breast_bin/breast-bin.data', sep=',', label=True)
breast_dataset.summary()

feat_0     feat_1     feat_2     feat_3     feat_4     feat_5  \
mean     4.417740   3.134478   3.207439   2.806867   3.216023   3.486409   
median   4.000000   1.000000   1.000000   1.000000   2.000000   1.000000   
min      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
max     10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
var      7.917053   9.298082   8.819630   8.141527   4.896110  13.099601   

           feat_6     feat_7     feat_8  
mean     3.437768   2.866953   1.589413  
median   3.000000   1.000000   1.000000  
min      1.000000   1.000000   1.000000  
max     10.000000  10.000000  10.000000  
var      5.937114   9.311340   2.937284

In [9]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [10]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

Features ['feat_0', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6', 'feat_7', 'feat_8']
Label y


In [11]:
# write the same fila with a different name
from si.io.data_file import write_data_file
write_data_file('../datasets/breast_bin/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [13]:
from si.io.csv_file import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [14]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
# write the same file with a different name
from si.io.csv_file import write_csv
write_csv('../datasets/iris/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)

In [16]:
# random dataset
from si.data.dataset import Dataset
random_dataset = Dataset.from_random(150, 30, 4)
random_dataset.get_classes()

array([0, 1, 2, 3])

In [17]:
# from dataframe
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(150, 30))
df_dataset = Dataset.from_dataframe(df)
df_dataset.X

array([[0.27582031, 0.22091549, 0.71849499, ..., 0.90194648, 0.69883875,
        0.50472101],
       [0.25554598, 0.91948352, 0.88329901, ..., 0.70058027, 0.33038292,
        0.19459901],
       [0.68398012, 0.39927887, 0.34570929, ..., 0.99700576, 0.77513039,
        0.13815143],
       ...,
       [0.1565986 , 0.24079035, 0.75572141, ..., 0.98705846, 0.15228135,
        0.71954645],
       [0.96829653, 0.32400146, 0.63950952, ..., 0.87025604, 0.68666194,
        0.04257575],
       [0.85425513, 0.35989371, 0.87468779, ..., 0.55813434, 0.50358235,
        0.22487049]])

In [18]:
df_dataset.has_label()

False