### Avaliação 3 - Testing Functions PCA 

In [8]:
from si.decomposition.pca import PCA
import numpy as np
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

filename = 'C:\\Users\\Fofinha\\Desktop\\UNI\\MESTRADO\\2o ANO\\Sistemas Inteligentes\\si\\datasets\\iris\\iris.csv'

ds = read_csv(filename, sep = ',', features = True, label = True)

selector = PCA(n_components=4)
selector.fit_transform(ds)
print(selector.components)

[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]
 [ 0.58099728 -0.59641809 -0.07252408 -0.54906091]
 [ 0.31725455 -0.32409435 -0.47971899  0.75112056]]


In [3]:
selector.mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])