## Testing Dataset functions

In [1]:
from dataset import Dataset
import numpy as np

In [ ]:
#dropna()
x = np.array([[1, 2, 3], [3, 1, 3]])
y = np.array([5, 5])
features = ['X', 'Y', 'Z']
label = 'x'
dataset = Dataset(x, y, features, label)
dataset = dataset.dropna()  #não tem NA, só para o teste
print('Dataset 1: \n', dataset.X)

x2 = np.array([[1, 2, 3], [3, np.nan, 7]])
dataset2 = Dataset(x2, y, features, label)  #dataset com NA, compara results
print('Dataset 2:\n', dataset2.X)
dataset2.dropna()
print('Dataset 2 after dropna()):\n', dataset2.X)

Dataset 1: 
 [[1 2 3]
 [3 1 3]]
Dataset 2:
 [[ 1.  2.  3.]
 [ 3. nan  7.]]
Dataset 2 after dropna()):
 [[1. 2. 3.]]


In [14]:
#fillna() REVER FUNÇÃO
X = np.array([[1.0, 2.0, 3.0],
                  [4.0, np.nan, 6.0],
                  [7.0, 8.0, 9.0]])

y = np.array([0, 1, 2])

dataset = Dataset(X, y)
print(dataset.fillna('mean').X)

[[ 1.  2.  3.]
 [ 4. nan  6.]
 [ 7.  8.  9.]]


c:\Users\Fofinha\anaconda3\Lib\site-packages\si-0.0.1-py3.11.egg\si\data\dataset.py:162: RuntimeWarning: Mean of empty slice
  method = np.nanmean(col)


In [15]:
#remove_from_index()
X = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 2])
features = np.array(['a', 'b', 'c'])
label = 'y'
dataset = Dataset(X, y, features, label)
print(dataset.remove_from_index(1).X)

[[1 2 3]]
